# Questions de cours 

1.Qu'est-ce qu'un pixel ?

plus petit element d'une image que l'on peut avoir; il n'a qu'une seule couleur

2.Quel format de stockage utilise-t-on pour stocker un pixel ?

RGB --> 255 pour chaque, donc 8bits (24bits : ancien format)
Nouveau format : RGBA
A:luminensce de 0 à 255 (donne plus de contraste)

3.Donner la suite de 0 et de 1 permettant de stocker une image de 2 fois 2 qui part du noir en haut à gauche
et devient plus rouge en allant à doite et plus bleu en allant vers le bas.

plus rouge en allant à droite

# Matrices

Créer une matrice avec 3 lignes et 4 colonnes

In [1]:
#définir la matrice sans utiliser de boucles comme une liste de liste
mat_liste = [[0, 0, 0],[0,0,0],[0,0,0]]

#définir la matrice comme un numpy array à deux dimensions
import numpy as np
mat_numpy = np.array(mat_liste)
print(mat_numpy)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Afficher le nombre de lignes et de colonnes de `mat_liste` et de `mat_numpy`.

In [2]:
nb_lignes = len(mat_liste)
nb_colonnes = len(mat_liste[0])

mat_numpy.shape[1]  # donne la forme (taille sous forme de tuple qui donne le nombre de ligne et de colonne)

3

Remplir `mat_numpy` de 9 en utilisant deux boucles sur les index de la matrice.

In [3]:
def rempli9(matrice):
    for i in range(matrice.shape[0]):
        for j in range(matrice.shape[1]):
            matrice[i][j] = 9

rempli9(mat_numpy)
print(mat_numpy)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


Maintenant, remplir la matrice de 8 en utilisant les fonctions spécifiques de numpy, sans faire de boucle. Consulter la documentation de numpy pour trouver une solution.

In [4]:
def rempli8(matrice):
    matrice[:] = 8

rempli8(mat_numpy)
print(mat_numpy)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


Créer une liste de taille 50 qui ne contient que des 3, en utilisant la compréhension de liste.
Créer ensuite une matrice comme liste de listes dont la première ligne contient des 1, la deuxième des 2 ...

In [10]:
mtce = [[3 for i in range(10)] for j in range(10)]
mtce
mtce2=[[j+1 for i in range(10)]for j in range(10)]
mtce2

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
 [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
 [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
 [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
 [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
 [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
 [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
 [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]]

# Matrice de Pixels

On va importer la librairie PIL pour charger et afficher des images. On importe aussi tkinter pour l'interface d'ouverture de fichier.

In [7]:
import PIL as pil
from PIL import Image
from PIL import ImageTk 

La fonction `save` permet de stocker la matrice de pixels passée en paramètre `matPix` dans un fichier spécifié par `filename`.
La fonction `load` renvoie la matrice représentant l'image stockée dans le fichier `filename`. 

In [11]:
def save(matPix, filename):
    Image.fromarray(matPix).save(filename)

def load(filename):
    return np.array(pil.Image.open(filename))
    

Créer une matrice de pixels de taille 100x100 ainsi qu'une fonction qui met à vert les pixels de la moitié gauche de l'image et à bleu les pixels de moitié droite.
Afin de visualiser l'image obtenue, on utilisera la fonction `save` et on ouvrira le fichier ainsi généré. On utilisera ensuite la méthode show de PIL.

In [15]:
#definir une nouvelle matrice 100x100
matVB= np.empty((100,100,3),dtype=np.uint8)

#utiliser une double boucle
def rempliVB(matrice):
    for i in range(matrice.shape[0]):
        for j in range(matrice.shape[1]):
            if j>50:
                matrice[i][j] = (0, 255, 0)
            else:
                matrice[i][j] = (0, 0, 255)

#alternativement, utiliser les slices de numpy
def remplirBR(matrice):
    matrice[:,0:49] = (0, 0, 255)  # à gauche toutes les lignes à droite toutes les colonnes
    matrice[:,50:] = (255,0,0)

    
rempliVB(matVB)
save(matVB,"vertbleu.png")

En vous servant de la fonction `load`, calculer le nombre de pixels dans une image `.bmp` de votre choix, puis calculer la taille de l'image en octets. Comparer avec la taille donnée par votre machine.

In [18]:
mat=load("test.bmp")
nbrPixel = mat.shape[0]*mat.shape[1]
taille = nbrPixel*3
taille

120000

Modifier l'image que vous avez créé précédemment en ajoutant un rectangle noir au milieu de l'image.

In [16]:
matrice=load("vertbleu.png")

def ajouteCarreNoir(mat):
    mat[25:75,25:75] = (0, 0, 0)

ajouteCarreNoir(matrice)
save(matrice,"vertbleumodif.png")

De la même manière ajouter un filtre qui ne conserve que la composante verte d'une image.

In [22]:
matrice=load("cheetah.png")

#avec une boucle
def filtre_vert(mat):
   for i in range(mat.shape[0]):
      for j in range(mat.shape[1]):
         mat[i][j] = (0, mat[i][j][1], 0)

#avec les slices de numpy
def filtre_bleu(mat):
   mat[:,:,(0,1)] = 0

filtre_bleu(matrice)
save(matrice,"filtre.png")

Créer une méthode qui permet d'afficher le négatif de l'image (on inverse la luminosité).

In [23]:
matrice=load("cheetah.png")

def negatif(mat):   
    mat[:] = 255-mat[:]  # 255- la valeur de la couleur qu'on avait

negatif(matrice)
save(matrice,"negatif.png")

Créer une méthode qui permet d'afficher le symétrique de l'image par rapport à la droite verticale en son milieu.

In [26]:
matrice=load("cheetah.png")

def symetrique(mat):
    temp= np.empty(mat.shape,dtype=np.uint8)   
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            temp[i][j] = mat[i][mat.shape[1] - j - 1]
    return temp

save(symetrique(matrice),"sym.png")